spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳
    lease-expiration-duration-in-seconds: 10 # 失效时间
    #prefer-ip-address: true  # 以ip地址注册到服务中心，互相注册使用ip，单节点部署分布式集群时不用配置
    
    
envirment： dev 
